# Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r requirements.txt", "pip install -r requirements-postgres.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && python load_fixtures.py && gunicorn main.wsgi --bind 0.0.0.0:$PORT"
